# CONUS 404 SP to P

In [1]:
import os
import sys
import numpy as np
import xarray as xr
import pandas as pd
from glob import glob

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

## CONUS 404 outputs

In [3]:
day = 120

In [4]:
fn_2d_full = sorted(glob('/glade/campaign/collections/rda/data/d559000/wy*/*/wrf2d*'))
fn_2d = fn_2d_full[day]
fn_3d = fn_2d[:62] + '3d' + fn_2d[64:]

ds_2d = xr.open_dataset(fn_2d)
ds_3d = xr.open_dataset(fn_3d)

## CONUS 404 static

In [5]:
fn_static = '/glade/campaign/collections/rda/data/d559000/INVARIANT/wrfconstants_usgs404.nc'
ds_static = xr.open_dataset(fn_static)

In [6]:
SP = ds_2d['PSFC'].values[0, ...]

In [7]:
P_bot = ds_2d['P'].values[0, ...]

In [8]:
P = ds_3d['P'].values[0, ...]

In [ ]:
slice(570, 905+1, 1), south_north=slice(200, 535+1, 1)

In [17]:
P_mean = P[:, 200:535+1, 570:905+1].mean(axis=(1, 2))

In [29]:
level_pick = [0, 3, 6, 9, 12, 15, 18, 21, 24, 30, 36, 42]

In [30]:
P_mean[level_pick] / 100

array([969.0557 , 946.9495 , 914.8635 , 866.86975, 801.2966 , 715.56213,
       610.4938 , 506.1178 , 416.7068 , 275.68964, 175.15102, 105.2876 ],
      dtype=float32)

In [ ]:
1000, 960, (x)940, 920, 880, 850, 800, 750, (x)680, 610, 500, 420, 280, (x)180, 100 hPa

In [17]:
C1F = ds_static['C1F'].values[0, ...]
C2F = ds_static['C2F'].values[0, ...]
C3F = ds_static['C3F'].values[0, ...]
C4F = ds_static['C4F'].values[0, ...]

In [18]:
C1H = ds_static['C1H'].values[0, ...]
C2H = ds_static['C2H'].values[0, ...]
C3H = ds_static['C3H'].values[0, ...]
C4H = ds_static['C4H'].values[0, ...]

In [19]:
ZNU = ds_static['ZNU'].values[0, ...]
ZNW = ds_static['ZNW'].values[0, ...]

P_TOP = ds_static['P_TOP'].values
P00 = ds_static['P00'].values
PB = ds_static['PB'].values

```
float ZNU(Time, bottom_top) ;
            ZNU:description = "eta values on half (mass) levels" ;
            ZNU:units = "" ;
            ZNU:stagger = "" ;

float ZNW(Time, bottom_top_stag) ;
        ZNW:description = "eta values on full (w) levels" ;
        ZNW:units = "" ;
        ZNW:stagger = "Z" ;
```

In [36]:
P = ZNU * (SP[0, 0] - P_TOP) + P_TOP

array([100913.43  , 100260.63  ,  99493.34  ,  98613.984 ,  97625.414 ,
        96530.05  ,  95274.98  ,  93808.71  ,  92139.93  ,  90278.72  ,
        88235.195 ,  85969.43  ,  83446.29  ,  80686.945 ,  77714.5   ,
        74507.79  ,  71052.36  ,  67386.71  ,  63550.285 ,  59734.55  ,
        56106.434 ,  52657.74  ,  49381.746 ,  46271.72  ,  43320.44  ,
        40520.695 ,  37866.71  ,  35352.227 ,  32971.    ,  30717.736 ,
        28586.658 ,  26572.477 ,  24669.9   ,  22874.117 ,  21180.318 ,
        19583.213 ,  18078.951 ,  16663.684 ,  15333.083 ,  14082.818 ,
        12909.041 ,  11808.387 ,  10777.482 ,   9812.484 ,   8910.023 ,
         8067.213 ,   7281.168 ,   6549.0005,   5867.3438,   5269.3916],
      dtype=float32)

In [39]:
C3H * (SP[0, 0] - P_TOP) + C4H * P_TOP

array([95913.43   , 95260.63   , 94493.34   , 93613.984  , 92625.414  ,
       91530.05   , 90274.98   , 88808.71   , 87139.93   , 85278.72   ,
       83235.195  , 80969.43   , 78446.29   , 75686.945  , 72714.5    ,
       69507.79   , 66052.36   , 62386.71   , 58550.285  , 54734.55   ,
       51106.434  , 47657.74   , 44381.746  , 41271.72   , 38320.44   ,
       35520.695  , 32866.71   , 30352.229  , 27971.002  , 25717.736  ,
       23586.658  , 21572.477  , 19669.9    , 17874.117  , 16180.318  ,
       14583.213  , 13078.951  , 11663.685  , 10333.083  ,  9082.818  ,
        7909.0415 ,  6808.386  ,  5777.4824 ,  4812.4844 ,  3910.0234 ,
        3067.2131 ,  2281.1677 ,  1549.0004 ,   867.34393,   269.39136],
      dtype=float32)

In [40]:
print(P[0, 0])

[100909.805 100905.07  100906.02  ... 100914.09  100913.61  100913.43 ]


In [41]:
SP[0, 0]

101211.2

In [43]:
P_bot[0, 0]

100909.805